### ISSUE TITLE
Bug: Bot stickies comments multiple times

### ISSUE THREAD

**Issue by zonination** [zonination/oc-bot#1]
Occasionally, the OC-Bot will "bug out" and comment multiple times on the same thread, oftentimes hours after the original posting.

**Some examples of this in action:**
* https://redd.it/7yozwj
* https://redd.it/8edsz4
* https://redd.it/8tqipo
* https://redd.it/87be86

**Bug characteristics:**
* "Author's Citations" links to a different comment (from the OP) every time. This is undesirable since it throws off the actual author's citations.
* Number of comments on the thread doesn't seem to be a factor.
* Username doesn't seem to be a factor.
* Post title doesn't seem to be a factor.
* It doesn't seem to be a regularly occurring bug, but it could be vastly under-reported.

**Here are things that have been tried, and their results:**
* Rebooting the bot doesn't fix it.
* Obviously, removing the thread and letting it fall off the Hot 100 will prevent it from commenting, but this is an undesirable solution.

**Comment by jonchun** [comment]
I'd love to take a crack at this. It's 24 days old, but I'm assuming there has been no progress on the bug?

**Comment by jonchun** [comment]
Took a peak at it today. While there are major issues with all of the code that I think warrants a rewrite, here would be some code that looks suspicious to me, and is likely to be the cause. (i haven't tested this)

The key symptom here is the following:
> "Author's Citations" links to a different comment (from the OP) every time. This is undesirable since it throws off the actual author's citations.

`comments = [comment for comment in [item for item in reddit.redditor(self.author).new(limit=100) if str(type(item)) == "<class 'praw.models.reddit.comment.Comment'>"] if comment.submission == self.submission]`

This filters the submissions locally. This means if an author has recent items elsewhere, the following scenario could happen.

- Author has 90 recent submissions unrelated to the OC submission. Author's 90-100th submissions are all in the relevant OC submission (their first comment linking to data, as well as them responding to other users). 

- The OP makes another post, knocking their current 100th's item out of their most recent 100. This 100th item was also the comment with citations. This means that to the bot, out of the most recent 100 it is given, the "oldest" comment is now the previously 99th item. The bot will then process the following line

`if self.check_database(oldest.id) is not True:`

and proceed because it wasn't previously in the database. You probably don't see this bug very often because submissions will naturally die out and drop out of HOT 100 before a user has a chance to rack up 100 recent combined comments/submissions, but the more prolific users could definitely trigger this.

**Comment by zonination** [comment]
Fantastic. I was wondering what was going on.

I've been working on Version 2.0, which I will be uploading shortly. This all has to do with the fact that it's searching for the oldest *comment*, and logging *that comment* individually. All I have to do to prevent this bug log the *submission*.

Also, the entire thing will be reworked shortly. But if this bug crops up with the new version, we'll know what to do.
